### ISSUE TITLE
Cannot have multiple instances

### ISSUE THREAD

**Issue by vectorjohn** [ekallevig/jShowOff#1]
This claims to work for multiple instances.  It does not because when you create an instance you use an ID attribute (jshowoff).  

It could be fixed if a unique ID was generated for each instance.

**Comment by vectorjohn** [comment]
hmm.  I see now that multiple instances is a future feature.

**Comment by ekallevig** [comment]
Yeah it shouldn't be tough to fix, just haven't gotten around to it yet.

**Comment by vectorjohn** [comment]
I made a fix that has minimal changes (which means there is probably a better way).  If you want I can send you a patch or something.  It basically generates a random ID for each instance and uses that everywhere it used #jshowoff.  Its working.

**Comment by ekallevig** [comment]
Cool man.  Yeah send it over and I'll add it in.  I'd love to see your implementation when you're done too!

**Comment by vectorjohn** [comment]
I'm at work right now.  I just created my github account to write this.  I don't know how to send patches at stuff so I'll figure it out at home when I'm on my own time tonight.

**Comment by ekallevig** [comment]
Yeah I'm new to GitHub as well, not sure how it works outside of basic commits, etc.  My email address is ekallevig@gmail.com.

**Comment by ekallevig** [comment]
You can now invoke multiple instances and every instance gets unique classes added to the elements for styling and scope purposes.

**Comment by vectorjohn** [comment]
Cool, looks good.  Sorry, I dropped the ball on that, I got busy with something else.

**Comment by AshMcConnell** [comment]
Hi Guys, Is there an example of creating multiple instances of different sizes?  The size seems to be taken from the .jshowoff class?  I would like to use jshowoff for a banner in my webpage and also for my screenshots.  Is this possible?

Thanks!
Ash

**Comment by AshMcConnell** [comment]
Ah, I got it working by specifying a width and height for the div id in question, it overrides the .jshowoff class.  Thanks for a great, simple and effective lib!
