### ISSUE TITLE
Icons in controls?

### ISSUE THREAD

**Issue by cperisson** [ekallevig/jShowOff#12]
Hi Erik! jShowOff works great!

Some way to put html/images in controls (play, next, etc.)?

Thanks for your help

Claudio

**Comment by ekallevig** [comment]
Hi Claudio -- yes, each instance and element in the jshowoff rotator has a unique class, so the easiest way to add icons to the buttons is to target the element with the class in CSS and use the <code>background-image</code> property to assign an icon.  Good luck!

<strong>Edit</strong>: Here's an example of how you might do it:

```
.jshowoff-1-play {
    padding-left: 30px;
    background-image: url(/img/someicon.png) no-repeat 0 0;
}
```

-Erik Kallevig

**Comment by mbeyaz** [comment]
Hi Erik;

I cant solve unique images do u give any sample pages or samples us ?

Thanks
Muharrem

**Comment by mbeyaz** [comment]
my unique images files has ;

.jshowoff-play {
    padding-left: 30px;
    background-image: url('img/baslat.jpg') no-repeat 0 0;
}

.jshowoff-stop {
    padding-left: 30px;
    background-image: url('img/durdur.jpg') no-repeat 0 0;
}

**Comment by mbeyaz** [comment]
Hi, I'm sorry I'm standing, but continuously, and then in internet explorer because of the css, but somehow I can not undo the problem, apart from that play, pause buttons, and digit of the image I want to give a special urgency in this regard would be happy to answer you type. regards ...
