### ISSUE TITLE
Background color forced to white?

### ISSUE THREAD

**Issue by chrisemersonnc** [ekallevig/jShowOff#2]
Hey there - love the plugin!

I'm using PNGs with transparent regions but no matter how I hack the CSS the background color of the jShowOff is white. Is there a way to let it be transparent so I can see through it to the body background color or wallpaper?

Thanks

**Comment by chrisemersonnc** [comment]
Sorry - this was a user error! I /fail!

/blush

please delete

**Comment by ekallevig** [comment]
Glad you got it working.
