### ISSUE TITLE
Don't animate when scroll with the mouse

### ISSUE THREAD

**Issue by elrafael** [ekallevig/jShowOff#27]
Hi.

First of all, great job ;)

I can't find a way (i don't know if exists) to stop the animation on mouseover.
This is the big deal:
- We have a vertical scrollbar. When I scroll the page down if the mouse, and if it is over the image, the plugin goes to the next image.

You can check it: http://www.aptca.pt/novo/ It's the first image, of a food (hum hum).
To simulate, just stop the mouse on the image and then try to roll with the rolling wheel.
Here is a screencast to better understand: http://screenr.com/7n6 (it's short, 0:35)

I checked the "Control-less, Effect-less Demo" example on your website, but I wish i have the animation but not when i scroll the mouse.

I checked the code too, but can't find any instance about mouse effects.

Sorry about my wired English.

Regards
Rafael V. de Oliveira

**Comment by ekallevig** [comment]
Set the 'hoverPause' option to false. Options listed here: http://ekallevig.com/jshowoff/
