### ISSUE TITLE
2 x #thumbFeatures side by side?

### ISSUE THREAD

**Issue by isntworkdull** [ekallevig/jShowOff#30]
Hi I am working on a redesign, and am using this script (excellent script btw), however i am struggling to get 2 x #thumbFeatures to line up side by side. They always appear vertically... before i carry on trying to figure this out just want to see if someone could tell me if its not possible to have 2 versions of these sliders next to each other horizontally. You can see what i am trying to do here: http www [dot] cctvcameras [dot] me.uk

Any advice / Help much welcome.

**Comment by ekallevig** [comment]
Yes it's possible to have two of these next to each other.  It's just a matter of getting the CSS right -- I suggest digging in with Firebug or Webkit Inspector to see where the problems are with the CSS.
