### ISSUE TITLE
Animation "flashes" in Safari

### ISSUE THREAD

**Issue by robwilkerson** [ekallevig/jShowOff#32]
Works great in every other browser I've tried (including IE7/8), but in Safari there's a very noticeable flash when the animation begins. It's my first time using the extension so, in case my settings are contributing:

```
$('.show-off').jshowoff({
  effect: 'fade',
  speed:7000,
  changeSpeed: 3500,
  controls: false,
  links: false,
  hoverPause: true
});
```

**Comment by ekallevig** [comment]
What OS and what version of Safari?  I just tested it in Mac and not seeing a flash.
