### ISSUE TITLE
Play after selecting a slide

### ISSUE THREAD

**Issue by iaintodd** [ekallevig/jShowOff#33]
Hi,
How can you make it so that after clicking on a slide number the slide show doesn't pause but the slide is shown for the set time and then the slideshow continues?

thanks a lot!
Iain

**Comment by ekallevig** [comment]
This feature isn't currently available, but I'll add it to the wishlist and hopefully get to it at some point.  Otherwise, feel free to grab the source and modify yourself.

**Comment by wellingtonwong** [comment]
Hi,

Let me first say that this is a great plugin by sir ekallevig, ur a genius, it helped me a lot on most of the drupal sites i build. for those still looking for way for the slideshow to continue after clicking, u can use the jquery click function and setTimeout to resume the slideshow. here's the code: 

$('.jshowoff-slidelinks a').click(function(){
    setTimeout("$('.jshowoff-paused').click()",5000);
});

hope it helps,
wellington
