### ISSUE TITLE
jShowOff blocking Cufon

### ISSUE THREAD

**Issue by gurtfrobe** [ekallevig/jShowOff#35]
In each of my slides I have a <h1> with Cufon font replacement applied to it.

The first slide that loads has the correct font applied but then all the following slides revert to a system font, and when the first slide returns it too has reverted to a system font.

This is only happening to the jShowOff div. All other instances of Cufon on the site are fine.

I have tried altering the position of when the Cufon settings are loaded in but to no avail.

**Comment by ekallevig** [comment]
Unfortunately, the way jShowOff works currently doesn't work very well if the slides have other .js attached to them in some way b/c of how it clones the slides, etc.  I'm planning to rewrite this at some point to fix that issue, but I can't say when I'll be able to.  Sorry!

**Comment by gurtfrobe** [comment]
Ah bugger. Nevermind. Thanks for getting back to me!
