### ISSUE TITLE
Can thumbs be generated from HTML?

### ISSUE THREAD

**Issue by azzcatdesign** [ekallevig/jShowOff#36]
Hi Erik,

Great plugin! I had given up finding a slider that would work with flexible %-based layout. @PauldeWouters showed me your plugin.

Was wondering if it is possible to have thumbnail nav that doesn't require background images in CSS? The site I'm working on will be using photos from the MLS database. CSS bkgd images not going to be practical.

The Awkward slider http://www.awkwardgroup.com/sandbox/awkward-showcase-a-jquery-plugin/ works with main images resized and wrapped in another div w/thumb dimensions. That's a step in the direction I'm seeking for thumbs (but Awkward doesn't work w/flexible %)

Ideally, a flexible slider + on-the-fly generated thumb navigation would be ideal. But I don't know if that's possible.

Thanks,
Catherine

**Comment by ekallevig** [comment]
Hey -- right now it's only possible with CSS background images.  You could
potentially use an inline style for the background image to get it from the
database?

Erik

**Comment by azzcatdesign** [comment]
That was speedy! :)

Not sure about inline style database thing. I can do CSS, but not DB work or writing own JS.

Thanks!
