### ISSUE TITLE
Want to use images in place of Play, Pause, Next, and Previous

### ISSUE THREAD

**Issue by TomRyan** [ekallevig/jShowOff#4]
The problem with using images for the controls is that on the first click of any of the controls the Play/Pause image reverts to the img tag rendered as plain text. Is there a way around this?

**Comment by ekallevig** [comment]
I'm not sure how you're doing it with img tags, but you're right that every time you click play, it updates the link with the corresponding text and class names.

The best way to use images for the buttons is with background images and hiding the text with something like 'text-indent: -10000em'.  Have a look at http://truthonhealth.org to see how I did it there.

**Comment by TomRyan** [comment]
Of course! I'm a little ashamed for not having thought of this myself first. :(

I was trying to use img tags by putting the tags in place of the spots in the script that specified what the text of each control should be. So in place of "Play" I put "< img src='play.png'/ >".

**Comment by ekallevig** [comment]
Ah I see.  Yeah background images should do the trick. Good luck!
