### ISSUE TITLE
Transition and speed parameters have little effect

### ISSUE THREAD

**Issue by chillfinn** [ekallevig/jShowOff#5]
Hi,

not sure if I'm doing something wrong, but if I amend speed and changespeed variables, it has little effect - is there some limit on integer values? I'm trying to get a long play for each slide, followed by a smooth transition...using 0.1.0

**Comment by ekallevig** [comment]
Hm. There aren't limits on the integers.  If you can provide a link to your problem, I could take a look at debugging it.

**Comment by chillfinn** [comment]
Afraid I can't - however I've just found that a colleague has 'hacked' some of it - I will investigate, that's probably the problem :0 Cheers!
